version: '3.1'

services:
  article-db:
    image: postgres:latest
    container_name: article-db
    ports:
      - "6001:5432"
    environment:
      POSTGRES_USER: article
      POSTGRES_PASSWORD: article
      POSTGRES_DB: article
    volumes:
      - article-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6000:6379"  
    networks:
      - app-network
    volumes:
      - redis-data:/data
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
    
volumes:
  redis-data:
    driver: local
  article-db-data:  
    driver: local

