version: '3.1'

services:
  article-db:
    image: postgres:latest
    container_name: article-db
    ports:
      - "6001:5432"
    environment:
      POSTGRES_USER: article
      POSTGRES_PASSWORD: article
      POSTGRES_DB: article
    volumes:
      - article-db-data:/var/lib/postgresql/data
  
  article-db-cache:
    image: redis:latest
    container_name: article-db-cache
    ports:
      - "5001:6379" 
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge

volumes:
  article-db-data:  
    driver: local
  redis-data:
    driver: local  
