version: '3.1'

services:
  mail-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mail_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
        - EmailSettings__Email=caylaa827@gmail.com
        - EmailSettings__Password=dfyxzsjddwtdiafq
        - EmailSettings__Host=smtp.gmail.com
        - EmailSettings__DisplayName=Parking Services
        - EmailSettings__Port=587
        - Kafka__BootstrapServers=kafka:9092
        - Kafka__Topic=test-topic
        - Kafka__GroupId=26112003
    ports:
      - "5001:80"
    depends_on:
      - kafka
  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

networks:
  default:
