global using ShredKernel.BaseClasses;
global using BuildingBlocks.Behaviors;
global using BuildingBlocks.Exceptions;
global using BuildingBlocks.Pagination;
global using BuildingBlocks.Repository;
global using BuildingBlocks.CQRS.Commands;
global using BuildingBlocks.CQRS.Queries;
global using BuildingBlocks.CQRS.Handlers;
global using BuildingBlocks.CQRS.Common;